kind: pipeline
type: docker
name: default

steps:
- name: restore-cache
  image: plugins/volume-cache
  settings:
    mount:
    - ./vendor/bundle
    - ./vendor/bin
    restore: true
  volumes:
  - name: cache
    path: /cache

- name: bundle-install
  image: ruby:2.4.6
  commands:
  - bundle install --path=vendor/bundle --binstubs=vendor/bin --clean --quiet
  environment:
    RAILS_ENV: test

- name: rebuild-cache
  image: plugins/volume-cache
  settings:
    mount:
    - ./vendor/bundle
    - ./vendor/bin
    rebuild: true
  volumes:
  - name: cache
    path: /cache

- name: build-mecab
  image: ruby:2.4.6
  commands:
  - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
  # mecab
  - cd /drone/src/vendor/mecab
  - wget -O mecab-0.996.tar.gz 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE'
  - tar xzf mecab-0.996.tar.gz && cd mecab-0.996
  - ./configure --enable-utf8-only && make && make install
  # mecab-ipadic
  - cd /drone/src/vendor/mecab
  - wget -O mecab-ipadic-2.7.0-20070801.tar.gz 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7MWVlSDBCSXZMTXM'
  - wget https://raw.githubusercontent.com/shirasagi/shirasagi/stable/vendor/mecab/mecab-ipadic-2.7.0-20070801.patch
  - tar xzf mecab-ipadic-2.7.0-20070801.tar.gz && cd mecab-ipadic-2.7.0-20070801
  - patch -p1 < ../mecab-ipadic-2.7.0-20070801.patch
  - ./configure --with-charset=UTF-8 && make && make install
  # mecab-ruby
  - cd /drone/src/vendor/mecab
  - wget -O mecab-ruby-0.996.tar.gz 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7VUNlczBWVDZJbE0'
  - tar xzf mecab-ruby-0.996.tar.gz && cd mecab-ruby-0.996
  - ruby extconf.rb && make && make install

- name: build-open_jtalk
  image: ruby:2.4.6
  commands:
  - export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
  # hts_engine_API
  - cd /drone/src/vendor/mecab
  - wget http://downloads.sourceforge.net/hts-engine/hts_engine_API-1.08.tar.gz
  - tar xzf hts_engine_API-1.08.tar.gz && cd hts_engine_API-1.08
  - ./configure && make && make install
  # open_jtalk
  - cd /drone/src/vendor/mecab
  - wget http://downloads.sourceforge.net/open-jtalk/open_jtalk-1.07.tar.gz
  - tar xzf open_jtalk-1.07.tar.gz && cd open_jtalk-1.07
  - sed -i "s/#define MAXBUFLEN 1024/#define MAXBUFLEN 10240/" bin/open_jtalk.c
  - sed -i "s/0x00D0 SPACE/0x000D SPACE/" mecab-naist-jdic/char.def
  - ./configure --with-charset=UTF-8 && make && make install
  # lame
  - cd /drone/src/vendor/mecab
  - wget http://downloads.sourceforge.net/lame/lame-3.99.5.tar.gz
  - tar xzf lame-3.99.5.tar.gz && cd lame-3.99.5
  - ./configure && make && make install
  # sox
  - cd /drone/src/vendor/mecab
  - wget http://downloads.sourceforge.net/sox/sox-14.4.1.tar.gz
  - tar xvzf sox-14.4.1.tar.gz && cd sox-14.4.1
  - ./configure && make && make install

- name: config-yml
  image: ruby:2.4.6
  commands:
  - cp -n config/samples/*.yml config/
  - cp -n config/samples/*.rb  config/
  - sed -i 's/localhost:27017/mongo:27017/g' config/mongoid.yml
  - cp -n config/defaults/webmail.yml config/
  - sed -i 's/#\ test_by:\ user/test_by:\ user/g' config/webmail.yml
  - sed -i 's/#\ test_user:/test_user:/g' config/webmail.yml
  - sed -i 's/#\ \ \ host:\ localhost/\ \ host:\ mail/g' config/webmail.yml
  - sed -i 's/#\ \ \ account:\ email/\ \ account:\ email/g' config/webmail.yml
  - sed -i 's/#\ \ \ password:\ pass/\ \ password:\ pass/g' config/webmail.yml

- name: rspec
  image: ruby:2.4.6
  commands:
  # chrome
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - apt-get update && apt-get install -y google-chrome-stable
  # font
  - apt install -y fonts-ipafont fonts-ipaexfont && fc-cache -fv
  # mecab
  - cd /drone/src/vendor/mecab/mecab-0.996 && make install
  - cd ../mecab-ipadic-2.7.0-20070801 && make install
  - cd ../mecab-ruby-0.996 && make install
  - echo '/usr/local/lib' >> /etc/ld.so.conf.d/usrlocal.conf && ldconfig
  # open_jtalk
  - cd /drone/src/vendor/mecab/hts_engine_API-1.08 && make install
  - cd ../open_jtalk-1.07 && make install
  - cd ../lame-3.99.5 && make install
  - cd ../sox-14.4.1 && make install
  - ldconfig
  # rspec
  - cd /drone/src
  - bundle check --path=vendor/bundle
  - bundle exec rspec
  environment:
    RAILS_ENV: test
    sandbox: 1
    allow_open_jtalk: 1
    ldap_host: 153.122.23.169
    CI: true
    TRAVIS: true

services:
- name: mongo
  image: mongo:3.4
  command: [ --smallfiles, --logpath=/dev/null ]
  ports:
  - 27017
- name: test_mail
  image: shirasagi/mail
  ports:
    - 143
    - 587

#volumes:
#- name: cache
#  host:
#    path: /tmp/cache/drone-shirasagi
